# Generated by Django 4.1.2 on 2022-10-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hitPoints',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom',
        ),
    ]
