# Generated by Django 4.1.2 on 2022-10-10 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0002_remove_character_charisma_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
