# Generated by Django 4.1.2 on 2022-10-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0006_character_charisma_character_constitution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='job',
        ),
        migrations.AddField(
            model_name='character',
            name='class',
            field=models.CharField(choices=[('barbarian', 'Barbarian'), ('bard', 'Bard'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('fighter', 'Fighter'), ('monk', 'Monk'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('sorcerer', 'Sorcerer'), ('warlock', 'Warlock'), ('wizard', 'Wizard')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(choices=[('acolyte', 'Acolyte'), ('charlatan', 'Charlatan'), ('criminal', 'Criminal'), ('entertainer', 'Entertainer'), ('folk hero', 'Folk Hero'), ('guild artisan', 'Guild Artisan'), ('hermit', 'Hermit'), ('noble', 'Noble'), ('outlander', 'Outlander'), ('sage', 'Sage'), ('sailor', 'Sailor'), ('soldier', 'Soldier'), ('urchin', 'Urchin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitPoints',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('dwarf', 'Dwarf'), ('elf', 'Elf'), ('halfling', 'Halfling'), ('human', 'Human'), ('dragonborn', 'Dragonborn'), ('gnome', 'Gnome'), ('half-elf', 'Half-Elf'), ('half-orc', 'Half-Orc'), ('tiefling', 'Tiefling')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='skillProficiency',
            field=models.CharField(choices=[('athletics', 'Athletics'), ('deception', 'Deception'), ('history', 'History'), ('insight', 'Insight'), ('intimidation', 'Intimidation'), ('investigation', 'Investigation'), ('medicine', 'Medicine'), ('nature', 'Nauture'), ('perception', 'Perception'), ('performance', 'Performance'), ('persuasion', 'Persuasion'), ('religion', 'Religion'), ('sleight of hand', 'Sleight of Hand'), ('stealth', 'Stealth'), ('survival', 'Survival')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.CharField(choices=[('hill dwarf', 'Hill Dwarf'), ('mountain dwarf', 'Mountain Dwarf'), ('high elf', 'High Elf'), ('wood elf', 'Wood Elf'), ('dark elf (drow)', 'Dark Elf (Drow'), ('lightfoot', 'Lightfoot'), ('stout', 'Stout'), ('black', 'Black'), ('blue', 'Blue'), ('brass', 'Brass'), ('bronze', 'Bronze'), ('copper', 'Copper'), ('gold', 'Gold'), ('green', 'Green'), ('red', 'Red'), ('silver', 'Silver'), ('white', 'White'), ('forest gnome', 'Forest Gnome'), ('rock gnome', 'Rock Gnome')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.SmallIntegerField(null=True),
        ),
    ]
