# Generated by Django 4.1.2 on 2022-10-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0007_remove_character_job_character_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('schedule', models.DateTimeField(max_length=100)),
                ('frequency', models.CharField(choices=[('once a week', 'Once A Week'), ('every other week', 'Every Other Week'), ('every two weeks', 'Every Two Weeks'), ('once a month', 'Once A Month'), ('other', 'Other')], max_length=100)),
                ('currentNumber', models.SmallIntegerField(null=True)),
                ('neededNumber', models.SmallIntegerField(null=True)),
                ('location', models.CharField(choices=[('in person', 'In Person'), ('online', 'Online')], max_length=100)),
                ('details', models.TextField(max_length=500)),
            ],
        ),
    ]
