# Generated by Django 4.1.2 on 2022-10-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0011_remove_character_campaign_campaign_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='characters',
        ),
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(to='dnd_app.character'),
        ),
    ]
