# Generated by Django 4.1.2 on 2022-10-14 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnd_app', '0014_alter_character_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dwarf', 'Dwarf'), ('elf', 'Elf'), ('halfling', 'Halfling'), ('human', 'Human'), ('dragonborn', 'Dragonborn'), ('gnome', 'Gnome'), ('half-elf', 'Half-Elf'), ('half-orc', 'Half-Orc'), ('tiefling', 'Tiefling')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hill dwarf', 'Hill Dwarf'), ('mountain dwarf', 'Mountain Dwarf'), ('high elf', 'High Elf'), ('wood elf', 'Wood Elf'), ('dark elf (drow)', 'Dark Elf (Drow'), ('lightfoot', 'Lightfoot'), ('stout', 'Stout'), ('black', 'Black'), ('blue', 'Blue'), ('brass', 'Brass'), ('bronze', 'Bronze'), ('copper', 'Copper'), ('gold', 'Gold'), ('green', 'Green'), ('red', 'Red'), ('silver', 'Silver'), ('white', 'White'), ('forest gnome', 'Forest Gnome'), ('rock gnome', 'Rock Gnome')], max_length=100)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.race')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnd_app.race'),
        ),
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnd_app.subrace'),
        ),
    ]
