# Generated by Django 4.1.2 on 2022-10-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0015_race_alter_campaign_user_subrace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrace',
            name='race',
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('dwarf', 'Dwarf'), ('elf', 'Elf'), ('halfling', 'Halfling'), ('human', 'Human'), ('dragonborn', 'Dragonborn'), ('gnome', 'Gnome'), ('half-elf', 'Half-Elf'), ('half-orc', 'Half-Orc'), ('tiefling', 'Tiefling')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.CharField(choices=[('hill dwarf', 'Hill Dwarf'), ('mountain dwarf', 'Mountain Dwarf'), ('high elf', 'High Elf'), ('wood elf', 'Wood Elf'), ('dark elf (drow)', 'Dark Elf (Drow'), ('lightfoot', 'Lightfoot'), ('stout', 'Stout'), ('black', 'Black'), ('blue', 'Blue'), ('brass', 'Brass'), ('bronze', 'Bronze'), ('copper', 'Copper'), ('gold', 'Gold'), ('green', 'Green'), ('red', 'Red'), ('silver', 'Silver'), ('white', 'White'), ('forest gnome', 'Forest Gnome'), ('rock gnome', 'Rock Gnome')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Subrace',
        ),
    ]
